version: '2'
services:
  cassandra:
    image: bitnami/cassandra:3
    volumes:
      - cassandra_data:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=kong
      - CASSANDRA_PASSWORD=kong
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
  cassandra2:
    image: bitnami/cassandra:3
    volumes:
      - cassandra2_data:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_USER=kong
      - CASSANDRA_PASSWORD=kong
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
  kong:
    image: bitnami/kong:1
    ports:
      - 18000:8000
      - 18443:8443
    environment:
      - KONG_MIGRATE=yes
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra,cassandra2
      - KONG_CASSANDRA_PASSWORD=kong
  kong2:
    image: bitnami/kong:1
    ports:
      - 28000:8000
      - 28443:8443
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra,cassandra2
      - KONG_CASSANDRA_PASSWORD=kong
volumes:
  cassandra_data:
    driver: local
  cassandra2_data:
    driver: local
